### ISSUE TITLE
Question: Sapper Environment Variables for SSR in CloudBuild/CloudRun

### ISSUE THREAD

**Issue by lasergoat** [mikenikles/sapper-on-cloud-run#12]
Mike, your blog article was really helpful! My sapper app connects to a database and uses some other secrets. I understand that I should use Google Cloud Secrets Manager for most of the secrets, however, for some things I still want environment variables. (I figure, for now using envs is simpler since I'd need to set up IAM and all that for my app to use secrets manager).

My rollup.config.js does something like this:

```
const processEnv = {
  "process.browser": true,
  "process.env.NODE_ENV": JSON.stringify(mode),
  "process.env.APP_SECRET": JSON.stringify(process.env.APP_SECRET),
  // ... more
};

export default {
  client: {
    input: config.client.input().replace(/\.js$/, ".ts"),
    output: { ...config.client.output(), sourcemap },
    plugins: [
      replace(processEnv), // <---- this
```

So, these variables would need to exist during the Cloud Build phase, then they get hardcoded into the code which is sent over to Cloud Run. So, using the environment vars in Cloud Run wouldn't work, unless I didn't use the replace() plugin for production builds.. so I suppose that's an option.

Either way, I'm curious how you handle these cases or if you already have some code you could add into this boilerplate? Just like in your guide, my project simply uses a Dockerfile, not a cloudbuild yaml.

Another question too, do you normally run DB migrations from your Dockerfile during Cloud Build as well?

**Comment by lasergoat** [comment]
Ok, I did get a simple solution for this - and if you want it might be a good thing to factor into your boilerplate or blog article. Let me know if you think a PR would be good - it doesn't really touch the committed code though.

[Here](https://cloud.google.com/cloud-build/docs/securing-builds/use-encrypted-secrets-credentials#yaml) is the Gcloud Doc where I learned this approach.

The solution gives your Codebuild docker file access to a .env file just like you might have locally.
Plus it keeps the app secrets like db password, or other api keys in the Secrets manager.

I simply made a secret in the secret store of my entire .env file. Then, in cloud build, I added this step in my trigger which uses an "inline" configuration. _(this was the configuration which was autogenerated for my when I made the trigger)._

you add a new step like this:

```
  - name: gcr.io/cloud-builders/gcloud
    args:
      - '-c'
      - >-
        gcloud secrets versions access latest
        --secret=production-config-secret-dotenv
        --format='get(payload.data)' | tr '_-' '/+' | base64 -d > app/.env
    entrypoint: bash
```

_this code is mostly from ["Using Secrets Manager > Item 4"](https://cloud.google.com/cloud-build/docs/securing-builds/use-encrypted-secrets-credentials#store_credentials)_

This basically says, take the secret called `production-config-secret-dotenv` and paste it into my app/.env file. For most people this would just be .env but for me, it's in an app directory.

Then, when the Dockerfile copies the code into the image, it includes the dotenv file. 

Here is an image of the new step in the inline configuration:

<img width="818" alt="Screen Shot 2020-12-24 at 10 31 07 PM" src="https://user-images.githubusercontent.com/15964/103119406-cf99ad00-4638-11eb-95b1-d78e69576bbe.png">

**Comment by mikenikles** [comment]
Hey Daniel, I'm catching up here 😄.

Your approach with Secrets Manager looks reasonable and definitely better than storing environment variables in Cloud Build as they show up in the UI for anyone to see who has access.

From a security perspective, be careful with the client-side config. For example, `APP_SECRET` sounds like something you wouldn't want to end up in your client bundle. You may need `processClientEnv` and `processServerEnv` objects and use them accordingly in your `rollup.config.js` file where you have the client and server config for Sapper.

> **I'm curious how you handle these cases or if you already have some code you could add into this boilerplate?**

I don't handle this well at the moment. I turn Cloud Build substitutions into environment variables as seen here: https://github.com/mikenikles/your-analytics/blob/master/services/admin-api/cloudbuild.yaml#L40.
However, your approach is more secure. In my case, the unencrypted values of these env variables show up in the Cloud Build UI.

> **Do you normally run DB migrations from your Dockerfile during Cloud Build as well?**

I don't have an example of that because I run migrations manually at the moment. Automating it also means I need a way to deal with rollbacks, something I consider more effort to automate than dealing with it manually for the time being. I wouldn't run migrations in the Dockerfile though. That to me is a separate task I would add in my continuous delivery pipeline. To me, the Dockerfile's single purpose is to build the Docker image, nothing else.

I'll merge a PR with your code examples, I think that's a great addition.
